"""empty message

Revision ID: 0953e91b9a7d
Revises: 316bf7da28c4
Create Date: 2022-12-03 13:46:01.822923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0953e91b9a7d'
down_revision = '316bf7da28c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potential_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('job_offer_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('was_it_matched', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offer.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('matches')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_offer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offer.id'], name='matches_job_offer_id_fkey'),
    sa.ForeignKeyConstraint(['person_id'], ['user.id'], name='matches_person_id_fkey'),
    sa.PrimaryKeyConstraint('person_id', 'job_offer_id', name='matches_pkey')
    )
    op.drop_table('potential_match')
    # ### end Alembic commands ###
