"""empty message

Revision ID: 34ee605f0d06
Revises: 5595914507fe
Create Date: 2022-12-03 07:26:38.733895

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "34ee605f0d06"
down_revision = "5595914507fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_offer", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_on", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("updated_on", sa.DateTime(), nullable=True))

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_on", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("updated_on", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("updated_on")
        batch_op.drop_column("created_on")

    with op.batch_alter_table("job_offer", schema=None) as batch_op:
        batch_op.drop_column("updated_on")
        batch_op.drop_column("created_on")

    # ### end Alembic commands ###
