"""empty message

Revision ID: 70e4dc5d5d04
Revises: 
Create Date: 2022-12-03 06:21:23.302354

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "70e4dc5d5d04"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("recruiter_role", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "job_offer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("keywords", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("recruiter_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recruiter_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_offer")
    op.drop_table("user")
    # ### end Alembic commands ###
